# Generated by Django 3.1.3 on 2020-12-05 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('game_state', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('num_of_tiles_tba', models.IntegerField(blank=True, default=None, null=True)),
                ('current_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_index', models.IntegerField()),
                ('tile_type', models.CharField(blank=True, max_length=50)),
                ('tile_num', models.CharField(blank=True, max_length=50)),
                ('tile_pic', models.FileField(upload_to='')),
                ('tile_status', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_time', models.DateTimeField()),
                ('room_state', models.CharField(blank=True, max_length=50)),
                ('num_of_players', models.IntegerField()),
                ('game', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_game', to='mahjong.game')),
                ('user1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='room_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_user2', to=settings.AUTH_USER_MODEL)),
                ('user3', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_user3', to=settings.AUTH_USER_MODEL)),
                ('user4', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_user4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('profile_picture', models.FileField(blank=True, upload_to='')),
                ('game_history', models.ManyToManyField(related_name='past_game', to='mahjong.Game')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='last_tile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lasttile', to='mahjong.tile'),
        ),
        migrations.AddField(
            model_name='game',
            name='list_discarded',
            field=models.ManyToManyField(related_name='discarded', to='mahjong.Tile'),
        ),
        migrations.AddField(
            model_name='game',
            name='list_in_user1',
            field=models.ManyToManyField(related_name='user1', to='mahjong.Tile'),
        ),
        migrations.AddField(
            model_name='game',
            name='list_in_user2',
            field=models.ManyToManyField(related_name='user2', to='mahjong.Tile'),
        ),
        migrations.AddField(
            model_name='game',
            name='list_in_user3',
            field=models.ManyToManyField(related_name='user3', to='mahjong.Tile'),
        ),
        migrations.AddField(
            model_name='game',
            name='list_in_user4',
            field=models.ManyToManyField(related_name='user4', to='mahjong.Tile'),
        ),
        migrations.AddField(
            model_name='game',
            name='list_of_triple_1',
            field=models.ManyToManyField(related_name='triple1', to='mahjong.Tile'),
        ),
        migrations.AddField(
            model_name='game',
            name='list_of_triple_2',
            field=models.ManyToManyField(related_name='triple2', to='mahjong.Tile'),
        ),
        migrations.AddField(
            model_name='game',
            name='list_of_triple_3',
            field=models.ManyToManyField(related_name='triple3', to='mahjong.Tile'),
        ),
        migrations.AddField(
            model_name='game',
            name='list_of_triple_4',
            field=models.ManyToManyField(related_name='triple4', to='mahjong.Tile'),
        ),
        migrations.AddField(
            model_name='game',
            name='list_to_be_assigned',
            field=models.ManyToManyField(related_name='unassigned', to='mahjong.Tile'),
        ),
        migrations.AddField(
            model_name='game',
            name='new_added',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_added', to='mahjong.tile'),
        ),
        migrations.AddField(
            model_name='game',
            name='user1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='user2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='user3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_user3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='user4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_user4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
